export enum GenreTypeEnum {
  HORROR = 'HORROR',
  COMEDY = 'COMEDY',
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  MYSTERY = 'MYSTERY',
  DOCUMENTARY = 'DOCUMENTARY',
  DRAMA = 'DRAMA',
  FANTASY = 'FANTASY',
  SCI_FI = 'SCI_FI',
  ROMANCE = 'ROMANCE',
  THRILLER = 'THRILLER',
  ANIME = 'ANIME',
  CARTOON = 'CARTOON',
  UNKNOWN = 'UNKNOWN'
}
